-- ============================================================
-- AlphaBrief — schéma des tables machine (Postgres local, VPS)
-- ============================================================
-- Appliqué par `make db-apply` sur la base `alphabrief`, avant
-- migrations/2026_07_31_patrimoine_schema.sql.
--
-- ORIGINE — ce fichier dérive de db/schema.reference.sql, qui était
-- l'introspection de la base Supabase (spec OpenAPI de PostgREST) au
-- 2026-07-31 23:28. La référence reste au repo comme constat historique de
-- ce qui était déployé ; ELLE N'EST PLUS LA SOURCE DE VÉRITÉ. Celle-ci l'est,
-- et elle s'édite à la main : la base est désormais sur la même machine que
-- le code, `psql` la décrit mieux qu'une spec HTTP.
--
-- TROIS TABLES DE LA RÉFÉRENCE NE SONT PAS REPRISES — vestiges du SaaS :
--   api_usage    le compteur de quota freemium
--   user_scans   le suivi d'usage par utilisateur
--   profiles     email + plan + stripe_customer_id + lemon_subscription_id
--
-- Critère mécanique appliqué (CLAUDE.md, « Suppression »), pas l'intuition :
--   grep -rn "from('api_usage')"  src/ → 0 référence, dans tout le dépôt
--   grep -rn "from('user_scans')" src/ → 0 référence, dans tout le dépôt
--   grep -rn "from('profiles')"   src/ → 1 : src/app/api/settings/route.ts:15
-- Les deux premières n'ont jamais eu le moindre consommateur : elles ont été
-- créées depuis l'interface Supabase et n'ont jamais été déclarées au repo.
-- `profiles` en a un seul, la route settings, qui portait le plan tarifaire.
-- Un réglage mono-utilisateur n'a pas besoin d'une table indexée par user_id.
--
-- CE QUI N'EST PAS RECRÉÉ NON PLUS : `alerts` et `portfolio_holdings`.
-- Elles n'existaient déjà pas dans Supabase (PGRST205, vérifié le
-- 2026-07-31) alors que le frontend les interroge — 5 appels pour `alerts`.
-- La fonctionnalité d'alertes n'a jamais tourné. On ne recrée pas une table
-- pour faire taire du code mort : la surface se tranche au lot 4.
-- ============================================================


-- ── Isolation : pourquoi il n'y a aucune RLS dans ce fichier ─
--
-- Le schéma Supabase posait des policies parce que la base y est joignable
-- depuis l'Internet : la dernière ligne de défense devait être en SQL. C'est
-- d'ailleurs là qu'était le trou, `FOR ALL USING (true)` sans clause `TO`,
-- qui ouvrait ticker_scores en écriture à n'importe quel visiteur.
--
-- Ici, Postgres n'écoute que localhost et la machine n'a qu'un utilisateur.
-- Le problème ne se corrige pas : il n'existe plus. Reposer une couche de
-- policies serait un coût de maintenance sans gain de sécurité.


-- ── ticker_scores ───────────────────────────────────────────
-- La carte courante d'un ticker : un seul enregistrement par symbole, écrasé
-- à chaque scoring.

CREATE TABLE IF NOT EXISTS ticker_scores (
    id                  UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    ticker              TEXT NOT NULL,
    score_total         NUMERIC NOT NULL,
    score_fundamentals  NUMERIC NOT NULL,
    score_technicals    NUMERIC NOT NULL,
    score_momentum      NUMERIC NOT NULL,
    score_date          DATE NOT NULL DEFAULT CURRENT_DATE,
    computed_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    company_name        TEXT,
    sector              TEXT,
    exchange            TEXT,
    currency            TEXT,
    market_cap          NUMERIC,
    one_liner           TEXT,
    moat_tags           JSONB,
    score_label         TEXT,
    importance_items    JSONB,
    financials          JSONB,
    market_data         JSONB
);

-- Le daemon écrit en upsert `ON CONFLICT (ticker)`. Sans cette contrainte,
-- l'écriture échoue en « there is no unique or exclusion constraint matching
-- the ON CONFLICT specification » — l'erreur exacte qu'a levée la base
-- miroir tant qu'elle ignorait cette unicité, invisible pour l'introspection
-- OpenAPI qui ne lit que la clé primaire.
ALTER TABLE ticker_scores DROP CONSTRAINT IF EXISTS ticker_scores_ticker_key;
ALTER TABLE ticker_scores ADD  CONSTRAINT ticker_scores_ticker_key UNIQUE (ticker);


-- ── score_history ───────────────────────────────────────────
-- Une ligne par ticker et par scoring : la trajectoire, jamais écrasée.
--
-- ⚠ La colonne est `scored_at`, PAS `recorded_at`. La migration de mai
-- déclarait `recorded_at` et la base déployée a toujours utilisé `scored_at` ;
-- le writer envoyait donc un nom de colonne inexistant, l'insert partait en
-- PGRST204 et l'erreur était avalée par un `except` en WARNING. L'historique
-- ne s'est jamais écrit par ce chemin jusqu'au 2026-07-31.

CREATE TABLE IF NOT EXISTS score_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker      TEXT NOT NULL,
    score       NUMERIC NOT NULL,
    confidence  NUMERIC NOT NULL DEFAULT 0,
    scored_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS score_history_ticker_scored_idx
    ON score_history (ticker, scored_at DESC);


-- ── ticker_events ───────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ticker_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker      TEXT NOT NULL,
    event_date  DATE NOT NULL,
    label       TEXT NOT NULL,
    kind        TEXT NOT NULL,
    source      TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ticker_events_ticker_date_idx
    ON ticker_events (ticker, event_date DESC);

-- Deuxième contrainte invisible à l'introspection OpenAPI, du même genre que
-- ticker_scores.ticker. Preuve : core/providers/events_yf.py poste sur
-- `ticker_events?on_conflict=ticker,event_date,kind` avec
-- `Prefer: resolution=merge-duplicates` et reçoit 2xx en prod ; PostgREST
-- traduit ça en ON CONFLICT, qui exige une contrainte unique correspondante.
-- Corroboré par la reprise : 313 lignes pour 313 triplets distincts.
ALTER TABLE ticker_events DROP CONSTRAINT IF EXISTS ticker_events_ticker_date_kind_key;
ALTER TABLE ticker_events ADD  CONSTRAINT ticker_events_ticker_date_kind_key
    UNIQUE (ticker, event_date, kind);


-- ── watchlists / watchlist_tickers ──────────────────────────
-- `user_id` est conservé tel quel : la reprise de données porte la valeur
-- existante, et l'aplatir demanderait de réécrire les 9 lignes pour un gain
-- nul. La colonne devient un vestige inerte, pas un discriminant.

CREATE TABLE IF NOT EXISTS watchlists (
    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id     UUID NOT NULL,
    name        TEXT NOT NULL DEFAULT 'Ma watchlist',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS watchlist_tickers (
    id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    watchlist_id  UUID NOT NULL REFERENCES watchlists(id) ON DELETE CASCADE,
    ticker        TEXT NOT NULL,
    added_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS watchlist_tickers_watchlist_idx
    ON watchlist_tickers (watchlist_id);


-- ============================================================
-- Forward-test paper — 8 tables
-- ============================================================
-- Hors du périmètre patrimoine, gardé sur décision explicite : c'est la
-- seule mesure existante de « est-ce que la notation produit du résultat »,
-- et elle a enfin des données (32 rebalances, 56 jours de NAV).
--
-- Les triggers append-only de la migration d'origine sont reproduits :
-- l'immuabilité du journal est le seul argument de ces tables.

CREATE OR REPLACE FUNCTION forbid_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'Table append-only: opération % interdite sur %',
        TG_OP, TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS paper_portfolios (
    id               SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL UNIQUE,
    strategy         TEXT NOT NULL,
    initial_capital  NUMERIC NOT NULL,
    started_at       DATE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS paper_positions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id  SMALLINT NOT NULL REFERENCES paper_portfolios(id),
    ticker        TEXT NOT NULL,
    side          TEXT NOT NULL CHECK (side IN ('LONG','SHORT')),
    shares        NUMERIC NOT NULL,
    entry_price   NUMERIC NOT NULL,
    entry_date    DATE NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (portfolio_id, ticker)
);

CREATE TABLE IF NOT EXISTS paper_rebalances (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id       SMALLINT NOT NULL REFERENCES paper_portfolios(id),
    rebalance_date     DATE NOT NULL,
    action             TEXT NOT NULL
                       CHECK (action IN ('BUY','SELL','SHORT','COVER','GENESIS')),
    ticker             TEXT NOT NULL,
    shares             NUMERIC NOT NULL,
    price              NUMERIC NOT NULL,
    fees               NUMERIC NOT NULL DEFAULT 0,
    slippage           NUMERIC NOT NULL DEFAULT 0,
    score_at_decision  INTEGER,
    rationale          TEXT,
    prev_hash          TEXT,
    row_hash           TEXT NOT NULL UNIQUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_paper_rebalances_portfolio_date
    ON paper_rebalances (portfolio_id, rebalance_date DESC);

CREATE TABLE IF NOT EXISTS paper_nav_history (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id       SMALLINT NOT NULL REFERENCES paper_portfolios(id),
    date               DATE NOT NULL,
    nav                NUMERIC NOT NULL,
    cash_balance       NUMERIC NOT NULL DEFAULT 0,
    cash_interest      NUMERIC NOT NULL DEFAULT 0,
    borrow_cost        NUMERIC NOT NULL DEFAULT 0,
    daily_return       NUMERIC,
    cumulative_return  NUMERIC,
    drawdown           NUMERIC,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (portfolio_id, date)
);

CREATE TABLE IF NOT EXISTS paper_metrics (
    portfolio_id  SMALLINT PRIMARY KEY REFERENCES paper_portfolios(id),
    sharpe        NUMERIC,
    sortino       NUMERIC,
    max_drawdown  NUMERIC,
    win_rate      NUMERIC,
    alpha_vs_spy  NUMERIC,
    beta          NUMERIC,
    sample_days   INTEGER NOT NULL DEFAULT 0,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS paper_missed_rebalances (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id    SMALLINT NOT NULL REFERENCES paper_portfolios(id),
    scheduled_date  DATE NOT NULL,
    detected_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    reason          TEXT NOT NULL
                    CHECK (reason IN ('VPS_DOWN','FMP_ERROR','SCORING_INCOMPLETE',
                                      'MANUAL_SKIP','UNKNOWN')),
    details         JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS paper_corporate_actions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id    SMALLINT NOT NULL REFERENCES paper_portfolios(id),
    ticker          TEXT NOT NULL,
    action_type     TEXT NOT NULL
                    CHECK (action_type IN ('SPLIT','REVERSE_SPLIT','DIVIDEND',
                                           'SPINOFF','MERGER_CASH','MERGER_STOCK',
                                           'DELISTING','SUSPENSION')),
    effective_date  DATE NOT NULL,
    details         JSONB NOT NULL DEFAULT '{}',
    applied_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS paper_sofr_rates (
    date        DATE PRIMARY KEY,
    rate        NUMERIC NOT NULL,
    source      TEXT NOT NULL DEFAULT 'FMP',
    fetched_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Les triggers append-only sont posés APRÈS la reprise de données
-- (db/load_export.py les installe en dernier) : ils interdiraient l'UPDATE,
-- pas l'INSERT, mais on garde l'ordre explicite plutôt que de compter dessus.
DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['paper_rebalances','paper_nav_history',
                             'paper_missed_rebalances','paper_corporate_actions',
                             'paper_sofr_rates']
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS tr_%s_append_only ON %I', t, t);
        EXECUTE format(
            'CREATE TRIGGER tr_%s_append_only BEFORE UPDATE OR DELETE ON %I '
            'FOR EACH ROW EXECUTE FUNCTION forbid_mutation()', t, t);
    END LOOP;
END $$;
